branch:
  helper: 'master'
  label: 'Git branch'

ssh_user:
  helper: 'chalasr'
  label: SSH username

deploy_to:
  helper: ~
  label: 'Remote directory'

model_manager:
  helper: 'doctrine'
  label: 'Model manager'

symfony_env:
  helper: 'prod'
  label: 'Environment'

use_sudo:
  helper: 'false'
  label: 'Use sudo'

use_set_permissions:
  helper: 'true'
  label: 'Set permissions'

permission_method:
  helper: ':chmod'
  label: 'Permissions method'
  autocomplete: [':chmod', ':acl']

keep_releases:
  helper: 3
  label: 'Number of releases'
